### ISSUE TITLE
Can't run tests, i.e. test0.py and test1.py

### ISSUE THREAD

**Issue by andrekovac** [clairecut/clairecut-backend#7]
I get the following error when running `python test0.py` locally. Didn't get it to even this stage within in the docker container. Get the same error with the other test, too:

```
Traceback (most recent call last):
  File "test0.py", line 38, in <module>
    positions = cutter.getPositions()
  File "/Users/andrekovac/dev/__projects/clairecut/clairecut-backend/src/processor/cutter.py", line 56, in getPositions
    openCVImageBinary.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack
```

@BudickDa: could you take a look at it?!

**Comment by BudickDa** [comment]
Which version of OpenCV do you have installed? 
This error looks like you are using 2.x
You need 3.x

**Comment by andrekovac** [comment]
I see, I have version 2.x Will install 3.x and then test it again.

**Comment by BudickDa** [comment]
Changed the Dockerfile to use the OpenCV 3.1. 
Now it works.
